---
- name: Install Keepalived and Curl
  apt:
    name: 
      - keepalived
      - curl
    state: present
  register: apt_result
  until: apt_result is success
  retries: 5
  delay: 10

- name: Render Keepalived configuration
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'
  notify: Restart Keepalived

- name: Ensure Keepalived is running and enabled
  systemd:
    name: keepalived
    state: started
    enabled: yes