name: Destroy
on: workflow_dispatch
jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Inject HCP Terraform Config via Secrets
        working-directory: terraform
        run: |
          sed -i "s/__HCP_ORG__/${{ secrets.HCP_ORG }}/g" versions.tf
          sed -i "s/__HCP_WORKSPACE__/${{ secrets.HCP_WORKSPACE }}/g" versions.tf

      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          
      - name: Terraform Destroy
        working-directory: terraform
        env:
          TF_VAR_proxmox_api_url: ${{ secrets.PROXMOX_API_URL }}
          TF_VAR_proxmox_token_id: ${{ secrets.PROXMOX_TOKEN_ID }}
          TF_VAR_proxmox_token_secret: ${{ secrets.PROXMOX_TOKEN_SECRET }}
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        run: |
          terraform init
          terraform destroy -auto-approve